name: max_player
description: A new Flutter package project.
version: 1.1.1
homepage: https://github.com/abdorizak/max_player

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  http: ^0.13.6
  get: ^4.6.5
  universal_html: ^2.2.3
  wakelock: ^0.6.2
  youtube_explode_dart: ^1.12.4
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
