name: max_player
description: Max Player is a simple package to that helps you to play videos from your local, network and from the internet weather youtube, vimeo, etc.
version: 3.1.0
homepage: https://abdorizak.dev
repository: https://github.com/abdorizak/max_player
issue_tracker: https://github.com/abdorizak/max_player/issues

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  very_good_analysis: ^10.0.0
  video_player: ^2.10.1
  wakelock_plus: ^1.1.0
  youtube_explode_dart: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
