name: max_player
description: Max Player is a simple package to that helps you to play videos from your local, network and from the internet weather youtube, vimeo, etc.
version: 1.1.1
homepage: https://abdorizak.dev
repository: https://github.com/abdorizak/max_player
issue_tracker: https://github.com/abdorizak/max_player/issues

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  http: ^0.13.6
  get: ^4.6.5
  universal_html: ^2.2.3
  wakelock: ^0.6.2
  youtube_explode_dart: ^1.12.4
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
